In [61]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.impute import SimpleImputer as si
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import numpy as np
import pandas as pd

In [62]:
trains = pd.read_csv('train.csv', header=None)

x = pd.DataFrame(trains)
x = x.replace('?',np.nan)

imp = si(missing_values=np.nan ,strategy='most_frequent')
train = imp.fit_transform(x).astype(np.int)

# train_train = train[:-1000]
# train_test = train[-1000:]




In [63]:
train_train = train[:-500]
train_test = train[-500:]

model1 = SelectKBest(chi2, k=6)
model1.fit(train_train[:,:-1], train_train[:,-1])
train_train = model1.transform(train_train[:,:-1])
train_test = model1.transform(train_test[:,:-1])


In [65]:
from sklearn.neighbors import KNeighborsClassifier
# 最好效果32

knn = KNeighborsClassifier(n_neighbors=32)
knn.fit(train_train[:,:-1],train_train[:,-1])
knn.score(train_test[:,:-1],train_test[:,-1])

0.70399999999999996

In [35]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

model1 = SelectKBest(chi2, k=6)
model1.fit(train[:,:-1], train[:,-1])
# test = model1.transform(train_test[:,:-1])
model1.scores_

array([    4.11348844,  1817.68756381,  1102.42385902,   650.63012714,
        1718.87699602,    28.8164721 ,   349.4863609 ,   298.44440359,
         534.08840466,   600.31240866,   327.20486604,    43.06069056,
          14.52256822])

In [39]:
train[0]

array([2, 5, 2, 4, 3, 4, 1, 1, 0, 2, 3, 7, 1, 1])

In [37]:
model1.transform(train[:,:-1])

array([[5, 2, 4, 3, 0, 2],
       [5, 3, 5, 1, 0, 2],
       [3, 5, 4, 1, 1, 1],
       ..., 
       [1, 7, 3, 8, 0, 1],
       [5, 1, 2, 6, 2, 3],
       [3, 4, 4, 1, 0, 2]])

In [52]:
model1 = SelectKBest(chi2, k=6)
train = model1.fit_transform(train[:,:-1], train[:,-1])


In [58]:
train

array([[5, 2, 4, 3, 0, 2],
       [5, 3, 5, 1, 0, 2],
       [3, 5, 4, 1, 1, 1],
       ..., 
       [1, 7, 3, 8, 0, 1],
       [5, 1, 2, 6, 2, 3],
       [3, 4, 4, 1, 0, 2]])

In [56]:
train_train = train[:-1000]
train_test = train[-1000:]

In [57]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=32)
knn.fit(train_train[:,:-1],train_train[:,-1])
knn.score(train_test[:,:-1],train_test[:,-1])

0.69799999999999995